### ISSUE TITLE
Quest sheet question

### ISSUE THREAD

**Issue by parduz** [seastan/lotr-lcg-se-plugin#1]
Hello from Italy.
Is this the "official" LOTR plugin? the only result i had from google is this one, the help from the plugin itselfs points to a blog that doesnt exists anymore,

My question is:
could be implemented a quest sheet like this one?

![LOTR Booklets01](https://user-images.githubusercontent.com/9556348/158481171-d83f7162-a780-43ea-bbea-451f722dbc34.jpg)
![LOTR Booklets02](https://user-images.githubusercontent.com/9556348/158481176-9d281eaa-ed37-4972-acae-0dcbea330619.jpg)
I'm thinking at the centered logo, and the "red warning" in the 2nd page.
I've found no way to make a sheet like this.

**Comment by OleksandrBerchenko** [comment]
@parduz Unfortunately, no.  It's not the "official" LOTR plugin.  And you can't do a quest sheet with it.

But have you seen this: https://strangeeons.cgjennings.ca/download.html ?  If you install it, you can also install a LOTR plugin (inside the application, no need to download anything manually).  As far as I remember, it supports quest sheets, but I'm not sure it provides all the capabilities that you need.

**Comment by parduz** [comment]
> , it supports quest sheets, but I'm not sure it provides all the capabilities that you need.

Yup, it does just the "standard" quest sheets (smaller logo on the left column), that's why i was searching for the developers.

Do you know if the official one is stil developed, and where to contact the ppl behind it?

What this "unofficial" plugin does more or different?

Thanks :)

**Comment by OleksandrBerchenko** [comment]
@parduz

> Do you know if the official one is stil developed, and where to contact the ppl behind it?

In theory - yes.  A new version was announced a long time ago, but it's not been released yet.  You may try to contact https://github.com/HeavyKaragh .

> What this "unofficial" plugin does more or different?

It's a custom fork tuned for our automated scripts (not in this repo).  Long to explain :)  I'm afraid it's not usable without those scripts.

Thanks!
